### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by biohazardxxx** [sillyfrog/SonOTA#2]
hi,
I find it difficult to get the python 3 env setup for this script. Tried raspberry, wind10 and debian VM all had different errors while installing requirements via pip3.
So I was wondering if it is possible to get this script in a docker container? To make this ready to run out of the box.

Anyhow, great work!
Alex

**Comment by sillyfrog** [comment]
Hi,
I have looked at this, but unfortunately the Docker API has no way (that I have found), to get the IP address of the host. It would technically be possible to run, but a lot (most) of the safeguards would be lost.

If you find a way to get the IP address of the host, I'm happy to look at it (would be very simple).

That said, what issues have you had installing using pip? Maybe I can help and if others have similar issues, we'll have a solution.

**Comment by biohazardxxx** [comment]
Regarding docker I found: --net=host option in docker could do the trick to get the host ip. 
https://stackoverflow.com/questions/43316376/what-does-net-host-option-in-docker-command-really-do

Problem on windows was that the netifaces module was not available at python 3.6 and vs build tools needed to be installed. Also I needed to manually restart the sonoff module at stage two, to see the FinalStage wifi. 
But after all it worked ☺️

**Comment by sillyfrog** [comment]
I tried the `--net=host` but unfortunately in the container it only shows the bridge IP, not the actual host IP, so the script can't see the change.

I get what you mean re build tools, it is a pain, _however_, there are wheels for Python 3.5 (both 32 and 64 bit) on Windows, so I would suggest trying with Python 3.5, and the pip install should just work. Let me know if this works as I'll update the README as it may help others.

Cheers.

**Comment by biohazardxxx** [comment]
Yes with 3.5 it worked ok then. Thanks a lot!

**Comment by sillyfrog** [comment]
Great!

I have updated the README to reflect this for others as well.

Cheers.
