### ISSUE TITLE
Device Error Code 404

### ISSUE THREAD

**Issue by simonszu** [sillyfrog/SonOTA#4]
I have a problem flashing an S20 device. I have bought two of them, the first one went fine. Great work, much appreciated.
However, the second one couldn't download the firmware binaries. In stage 2, when the device should load the firmware from my computer, it clicks two times with its relais, and responds with an error code 404. The FinalStage SSID is never shown. 
After resetting the Device with 7-second-press on the button, the original ITEAD SSID is spawned. 

I have checked that i have the desired IP after joining my normal WiFi network, and i curled the URL provided to the device (so basically localhost, but since the flashing of the first device went fine, i doubt there are network issues), and this worked as well. 

So where could be my mistake? Both devices are exactly identical, bought at the same time from the same reseller.

**Comment by sillyfrog** [comment]
This sounds like the same issue here #1 

Do you know what version the Sonoff was on before you started (both for the working and the failed)? I'd like to try and record what version do and don't work.

If you can try updating the Sonoff firmware via the EWeLink app, that would be great, hopefully that gets it going. If it doesn't, we'll have to get a bunch more debugging in and work backwards from there.

Cheers.

**Comment by simonszu** [comment]
Ah, i didn't see your comment yet, but came to the same conclusion after scrolling up my tmux buffer and comparing the successful output with the failing output. The successful S20 came with firmware 1.5.5 preinstalled, and i noticed that the unsuccessful device had 1.5.2 installed. So i installed the EWleLink App (and maybe gave a bunch of chinese hackers access to my smartphone, but it's worth it :D) and installed 1.5.5 firmware.
After that everything went smoothly as expected. 

On a side note: The relais clicking i did not hear on the first device was because the first device was powered by 3.3v via an UART adapter after unsuccessfully trying to flash Tasmota via USB-UART, while the second device was directly plugged into an outlet. Turns out the relais need higher current than the low one provided by the UART adapter. 

So, maybe you can add a note to the README that S20 devices need at least firmware 1.5.5 to use SonOTA. Will check with an original Sonoff Device later, i have one lying around here which is collecting dust since the end of 2016, it should have a much older firmware.
