### ISSUE TITLE
never get SSID FinalStage

### ISSUE THREAD

**Issue by joshuascottpaul** [sillyfrog/SonOTA#5]
never get SSID FinalStage

i have S20

*** IMPORTANT! ***
** AFTER the first download is COMPLETE, with in a minute or so you should connect to the new SSID "FinalStage" to finish the process.
** ONLY disconnect when the new "FinalStage" SSID is visible as an available WiFi network.
This server should automatically be allocated the IP address: 192.168.4.2.
If you have successfully connected to "FinalStage" and this is not the IP Address you were allocated, please ensure no other device has connected, and reboot your Sonoff.
......2017-09-03 13:19:01,181 (WARNING) error on read: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)
..2017-09-03 13:19:05,636 (WARNING) error on read: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)
..

**Comment by sillyfrog** [comment]
Can you please send through the full output, including all of the JSON that's printed before this stage. That will include the errors that may have occurred and firmware version etc.
Cheers.

**Comment by pixiandreas** [comment]
I have the same error, the FinalStage is not showing up.
This is the output: 
andreas@andreas-ThinkPad-X250 (master):~/src/SonOTA$ python3 sonota.py 
Select IP address of the WiFi interface:
    0: 192.168.6.139
Select IP address [0]: 0
WiFi SSID: xxxxx
WiFi Password: xxxxx

Using the following configuration:
	Server IP Address: 192.168.6.139
	WiFi SSID: xxxxx
	WiFi Password: xxxxxr
** Now connect via WiFi to your Sonoff device.
** Please change into the ITEAD WiFi network (ITEAD-100001XXXX). The default password is 12345678.
To reset the Sonoff to defaults, press the button for 7 seconds and the light will start flashing rapidly.
** This application should be kept running and will wait until connected to the Sonoff...
..................................................................~~ Connection attempt
>> HTTP GET /10.10.7.1/device
<< {
    "apikey": "42d6ec77-484a-4cdf-9b1f-cb4809481606",
    "deviceid": "10000bb968",
    "accept": "post"
}
>> HTTP POST /10.10.7.1/ap
>> %s {
    "port": 8443,
    "password": "xxxxxx",
    "ssid": "xxxxxx",
    "serverName": "192.168.6.139",
    "version": 4
}
<< {
    "error": 0
}
~~ Provisioning completed
Starting stage2...
~~ Starting web server (HTTP port: 8080, HTTPS port 8443)
~~ Waiting for device to connect


*** IMPORTANT! ***
** AFTER the first download is COMPLETE, with in a minute or so you should connect to the new SSID "FinalStage" to finish the process.
** ONLY disconnect when the new "FinalStage" SSID is visible as an available WiFi network.
This server should automatically be allocated the IP address: 192.168.4.2.
If you have successfully connected to "FinalStage" and this is not the IP Address you were allocated, please ensure no other device has connected, and reboot your Sonoff.
..........

**Comment by sillyfrog** [comment]
Couple of things, can you confirm what version firmware and model the Sonff is (you'll need to install the EWeLink app).

Also, when it has printed "Starting stage2...", did your PC connect back to your WiFi network (the one showing as `xxxxxxxx` in the above)? It looks like it did given it printed the `IMPORTANT` line, but double checking. It may also be worth double checking the SSID and password is exactly correct (_both_ are case sensitive).

**Comment by donoo** [comment]
Hi,
I was also trying but  "FinalStage"  SSID is not appearing. 

**Details:**

Sonoff basic,
version is 1.5.5

I tried both on Mac and Windows 10 machines.

**On Mac I can see:**

" read: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1977)"

But on windows 10 machine, no error or warning is there.

**Comment by sillyfrog** [comment]
This project is now part of https://github.com/mirko/SonOTA - so I'm closing this here. If you are still having issues please open an issue there and I'll take a look if I can.
Please include the full output of the run (remember to remove your WiFi password), that may help narrow it down.
Cheers.
