### ISSUE TITLE
Slampher stuck in FinalStage

### ISSUE THREAD

**Issue by ComteZero** [sillyfrog/SonOTA#6]
Sonoff Slampher v2.0, latest sillyfrog/sonota. I've replaced the image_arduino.bin by my version of tasmota (5.6.1, set on my AP).
my firmware is ok as I've successfully flashed a Slampher v2.0 using the header on board and the unit runs fine.

FinalStage is visible and I  get the IP 192.168.4.2
The led is blinking with a 1sec period. The SSID FinalStage is still visible after more than an hour connected to it. 

Do you know how to reset a sonoff from FinalStage to ITEAD-10001xxx in order to retry the procedure?
I've tried severals combinations of short presses (3 short turns the led red) / long presses (5 secs turn the led off and then the led blink again). I've unplugged the device, still nothing.

as a workaround, I will flash this unit with the onboard header and try to flash another unit using sonota.
I really hope we will find a solution as I plan to buy more of these :)

I plan to try your script on Sonoff TH16, Sonoff POW and Sonoff Swith. 

Thank you.

Cz

**Comment by ComteZero** [comment]
another info: the unit has established a connection on port 8080 and the script responds correctly to any of the three GET request: ota/image_user1-0x01000.bin, ota/image_user2-0x81000.bin and image_arduino.bin

once the socket is closed, the ssid FinalStage is still visible and nothing change on the unit.

**Comment by sillyfrog** [comment]
Can you post the full output of a test run? (Remember to remove the WiFi password in the post).

Also, do you know what version of the Sonoff Firmware it has (normally 1.x.x, if it's 2.x then it's not something I have tested, but I'll see what I can figure out)?

Finally, have you also tried with the included version of Tasmota, there were a number of build options that had to be correct for it to work in my original testing (serial was slightly different, and I could then update again using different build options - part of the reason the included version is not updated :) )

**Comment by ComteZero** [comment]
Firmware: 1.6.2
I've successfully recovered the previous Slampher by flashing tasmota using the serial port.
I try your image_arduino.bin next and come back to you.

Cz

**Comment by ComteZero** [comment]
sorry 2.0 was the board version of the Slampher

**Comment by ComteZero** [comment]
Hi SillyFrog, you will find my logs attached. I've added some timestamps, ifconfig, iwlist scan and netstat.
Sonota script has successfully ended but the FinalStage SSID is still present, even after power cycling, presses long and short etc...

Hope this will help. I will also reflash this unit with a serial connection.

I've checked my Sonoff TH16 and the firmware is also 1.6.2
I'm waiting for your feedback before attempting to flash the TH16 with your script.

Regards,

CZ
[log-sonota-09_35_02.zip](https://github.com/sillyfrog/SonOTA/files/1289682/log-sonota-09_35_02.zip)

**Comment by sillyfrog** [comment]
It looks like it's connecting based on the netstat output, but the packets are not making it through... which is weird!

This is the line I'm looking at:
`tcp        0  14472 192.168.4.2:8080        192.168.4.1:1225        ESTABLISHED 7467/python3`

I'm away this week, but next week I'll be able to speak with someone who may know. I'm assuming a linux distro, can you tell me what version etc? I would also suggest turning off any `iptables` rules, and any other filtering you may have (unlikely, but I'm guessing at the moment!)

May also be worth checking the output of `arp -n`, or even trying to get the output from `tcpdump`, and seeing if there is anything obvious regarding what's going out and not coming back (include it with `-e` to get the ethernet level, I know it does some funky stuff at the Ethernet level, if you want to send me the output do something like `tcpdump -i wlan0 -e -n -s0 -v -w outputfile.pcap`, and send me the pcap file). Finally, it may also be worth trying on Windows or Mac (if easy), as it would be interesting if it gets further.

I have not tried with that version of the Sonoff (see the home page for the tested versions), but I have a few TH's on the way (should be here in a week or so), and I'll be better recording versions when I update those with this update process. I'll also be sure to update one to the latest Sonoff release and make sure it works.

**Comment by ComteZero** [comment]
Thank you for your feedback. I'm using a Raspbian Jessie as my lab machine. I do not own any Mac and i will not install python on my Win10 as it's a real pain :(

I do not have any iptables rules defined. I will make a tcpdump for my next try with the TH16.

Have a good week !

CZ

**Comment by sillyfrog** [comment]
This project is now part of https://github.com/mirko/SonOTA - so I'm closing this here. If you are still having issues please open an issue there and I'll take a look if I can.
Cheers.
