### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by TimmyOtool** [sillyfrog/SonOTA#7]
Got a 404 error and "FinalStage" SSID never visible.

2017-09-09 15:46:26,225 (DEBUG) << WEBSOCKET INPUT
2017-09-09 15:46:26,226 (DEBUG) << {
    "userAgent": "device",
    "apikey": "abe0aff1-d056-4905-91c6-9934722d075c",
    "deviceid": "10000e9c6d",
    "action": "query",
    "params": [
        "timers"
    ]
}
~~~ device sent action request,  acknowledging / answering...
~~~~ query
>> {
    "error": 0,
    "deviceid": "10000e9c6d",
    "apikey": "abe0aff1-d056-4905-91c6-9934722d075c",
    "params": 0
}
2017-09-09 15:46:27,489 (DEBUG) << WEBSOCKET INPUT
2017-09-09 15:46:27,489 (DEBUG) << {
    "error": 404,
    "userAgent": "device",
    "apikey": "abe0aff1-d056-4905-91c6-9934722d075c",
    "deviceid": "10000e9c6d",
    "sequence": "1504964786224"
}
2017-09-09 15:46:27,489 (DEBUG) ~~~ device acknowledged our action request (seq 1504964786224) with error code 404
2017-09-09 15:46:27,495 (INFO) 200 GET /ota/image_user2-0x81000.bin?deviceid=10000e9c6d&ts=686078705&sign=2611c90c33cef985370c40a26a15eee499cbcacfdd03ffe4ea049a8520e62a59 (192.168.0.120) 305.11ms
.......

*** IMPORTANT! ***
** AFTER the first download is COMPLETE, with in a minute or so you should connect to the new SSID "FinalStage" to finish the process.
** ONLY disconnect when the new "FinalStage" SSID is visible as an available WiFi network.

**Comment by sillyfrog** [comment]
It sounds similar to issues #1 and #4.

Are you able to confirm the device you are using and the Sonoff firmware version (the full output includes the `romVersion`). I have not seen it my self, but updating appears to sort it. If you can let me know the version both before an update, and after an update, and if it worked, that would be great as I can then put on the home page for others.

Cheers.

**Comment by TimmyOtool** [comment]
Here's the logs where the firmware appears
2017-09-09 15:20:10,208 (DEBUG) << {
    "userAgent": "device",
    "apikey": "c87fbf98-d625-449c-99b0-fb645ae606cd",
    "deviceid": "10000e9c6d",
    "action": "register",
    "version": 2,
    "romVersion": "1.5.2",
    "model": "ITA-GZ1-GL",
    "ts": 263
}
...
{
    "action": "upgrade",
    "deviceid": "10000e9c6d",
    "apikey": "2aec4d1c-eee6-465b-8154-937d0816974c",
    "userAgent": "app",
    "sequence": "1504963210235",
    "ts": 0,
    "params": {
        "binList": [
            {
                "downloadUrl": "http://192.168.0.2:8080/ota/image_user1-0x01000.bin",
                "digest": "97fe70d737390bbde7b8d208c79d590e29fc76962623c7bd198ee210210ea616",
                "name": "user1.bin"
            },
            {
                "downloadUrl": "http://192.168.0.2:8080/ota/image_user2-0x81000.bin",
                "digest": "e6d0cbb641542bd0a27e6c4628fc9331f1f5d3ac3afa42c9307569cf4d70fcdc",
                "name": "user2.bin"
            }
        ],
        "model": "ITA-GZ1-GL",
        "version": "23.42.5"
    }
}

**Comment by sillyfrog** [comment]
What device is it?

As per the README (the home page), it looks like v1.5.2 does not work (at least with some devices). However if you update using the EWeLink app to the latest Sonoff, you should be away. Let me know how you get on and the details, and I'll update the README further.

I have recently ordered a few more devices, so will be testing these as well and trying to figure out why its getting confused.

Cheers.

**Comment by TimmyOtool** [comment]
Thanks
It a sonoff basic and after upgrading to the last version (1.5.6), i was able to install the firmware

Cheers
