### ISSUE TITLE
feature: autojoin networks

### ISSUE THREAD

**Issue by krtschmr** [sillyfrog/SonOTA#8]
i was flashing 15 devices so far and it's annoying to switch wifis.

cant we do

    sudo iwlist eth0 scan | grep ITEAD

and if there is some return than we take that one with something like `nmcli d connect ITEAD#{id}`

then we disconnect from that (or join the original one) and then we listen for the `finalstage` and join and rejoin.

just an idea ;)

**Comment by sillyfrog** [comment]
Great idea!
I have only used this on Mac (and it would be different there), and no idea how (if?) this would be possible for Windows.

If I get a chance I'll see if I can take a crack at it - but also happy to accept PR's :) 

This project is now part of https://github.com/mirko/SonOTA - so I'm closing this here for the moment - but I'll keep it on my list of things to look at. Cheers.

**Comment by krtschmr** [comment]
on windows no chance at all, because of windows. 
it would be most likely a bonus for ubuntu or linux. simply run the installer and as soon the wifis appear, they autojoin into. makes the whole thing a 2 minute autorun, rather then scan&connect for myself.
