### ISSUE TITLE
Sonoff B1 local network

### ISSUE THREAD

**Issue by ageorgios** [sillyfrog/SonOTA#9]
Trying to flash Shonoff B1 bulb, the bulb does not advertise any ITEAD-XXX wifi network.
I connected to my Wifi router through the ewelink app.
How can I execute the script with the bulb on the local network and not on ITEAD-XXX network?

**Comment by sillyfrog** [comment]
You'll need to reset it back to defaults. Press the button for 7+ seconds until it's reset. It uses this initial configuration state to tell it to go to the local update server (rather than Sonoff).
So if already configured, you'll need to reset first.

**Comment by ageorgios** [comment]
I am talking about the Sonoff B1 bulb without button.. Please explain

**Comment by krokce** [comment]
Having the same issue with Sonoff 4CH Pro. The 4CH Pro is not broadcasting any wifi network when in pairing mode. The eWeLink App finds the device and connects without problems though, maybe through a hidden SSID? I guess it's the same way for B1 bulb...

**Comment by krokce** [comment]
@ageorgios: according to [B1 user guide](http://ewelink.coolkit.cc/?p=837) you can enter into pairing mode by turning off and on for 3 times (OFF–>ON–>OFF–>ON–>OFF–>ON), the time interval is 2s. Then the bulb will start breathing...

**Comment by sillyfrog** [comment]
Hmmm... I was assuming it was the same as the other devices. I don't have one so can't test, but you need to (somehow) connect your PC to the device while it's in configuration mode (so we can trick it to update locally rather than Sonoff). Maybe what krokce said will help. Sorry I can't help more.

**Comment by ageorgios** [comment]
Yes the OFF/ON three times puts the bulb into breathing mode but it does not broadcast any (at least not hidden) wifi, 

The eWelink app on B1 also finds it and connects like you say with 4CH Pro

**Comment by sillyfrog** [comment]
This project is now part of https://github.com/mirko/SonOTA - so I'm closing this here. If you are still having issues please open an issue there and I'll take a look if I can.
Unfortunately on this one I don't really know what else to look at as I don't have either on these devices.
